create table mission(
num int not null primary key auto_increment,
id char(20) not null,
nick char(20) not null,
category char(20) not null,
subject char(100) not null,
content text not null,
regist_day char(20),
deadline char(20),
num_of_mem int(2),
file_name_0 char(40),
file_name_1 char(40),
file_name_2 char(40),
file_name_3 char(40),
file_name_4 char(40),
file_name_5 char(40),
file_copied_0 char(35),
file_copied_1 char(35),
file_copied_2 char(35),
file_copied_3 char(35),
file_copied_4 char(35),
file_copied_5 char(35),
hit int,
foreign key(id) references member(id)
);